//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppraisalFeedBackAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Appraisal
    {
        public Appraisal()
        {
            this.Appraisees = new HashSet<Appraisee>();
        }
    
        public int Id { get; set; }
        public string ProjectName { get; set; }
        public short AppraisalYear { get; set; }
        public string AppraisalType { get; set; }
        public string CustomerEmail { get; set; }
        public string AppraisalStatus { get; set; }
        [JsonIgnore]
        public string ValidationKey { get; set; }
    
        public virtual ICollection<Appraisee> Appraisees { get; set; }
    }
}
